#!/usr/bin/env bash
set -euo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_NAME="${AHO_ENV_NAME:-AHOAnaSkill}"
RUNTIME_ENV_FILE="$SKILL_DIR/.aho-runtime.env"

find_conda() {
    if [[ -n "${AHO_CONDA_EXE:-}" && -x "$AHO_CONDA_EXE" ]]; then
        printf '%s\n' "$AHO_CONDA_EXE"
        return 0
    fi
    if command -v conda >/dev/null 2>&1; then
        command -v conda
        return 0
    fi

    local candidate
    local candidates=(
        "$HOME/soft/conda"/*/bin/conda
        "$HOME/miniforge3/bin/conda"
        "$HOME/mambaforge/bin/conda"
        "$HOME/miniconda3/bin/conda"
        "$HOME/anaconda3/bin/conda"
        "/opt/conda/bin/conda"
    )
    for candidate in "${candidates[@]}"; do
        if [[ -x "$candidate" ]]; then
            printf '%s\n' "$candidate"
            return 0
        fi
    done
    return 1
}

CONDA_EXE="$(find_conda)" || {
    echo "[x] conda is not installed or cannot be found."
    echo "    Set AHO_CONDA_EXE=/path/to/conda and rerun ./install.sh."
    exit 1
}

if "$CONDA_EXE" env list | awk '{print $1}' | grep -qx "$ENV_NAME"; then
    echo "[i] Updating env '$ENV_NAME'..."
    "$CONDA_EXE" env update -n "$ENV_NAME" -f "$SKILL_DIR/environment.yml" --prune
else
    echo "[i] Creating env '$ENV_NAME'..."
    "$CONDA_EXE" env create -f "$SKILL_DIR/environment.yml"
fi

chmod +x "$SKILL_DIR/bin/aho"
mkdir -p "$SKILL_DIR/data" "$SKILL_DIR/reports/figures" "$SKILL_DIR/reports/scripts"

{
    printf '# Generated by install.sh. Local runtime configuration for this skill copy.\n'
    printf 'AHO_CONDA_EXE=%q\n' "$CONDA_EXE"
    printf 'AHO_ENV_NAME=%q\n' "$ENV_NAME"
} > "$RUNTIME_ENV_FILE"

"$CONDA_EXE" run --no-capture-output -n "$ENV_NAME" python "$SKILL_DIR/scripts/aar_db.py" init \
    --db "$SKILL_DIR/data/aho.sqlite"

echo "[i] Checking environment..."
"$CONDA_EXE" run --no-capture-output -n "$ENV_NAME" python "$SKILL_DIR/scripts/check_env.py"

echo
echo "[ok] Installed AHOAnaSkill."
echo "Runtime config:"
echo "    $RUNTIME_ENV_FILE"
echo "Add this to PATH if desired:"
echo "    export PATH=\"$SKILL_DIR/bin:\$PATH\""
